# site settings
title: Martin Buxmann
subtitle: Personal Website
email: mbuxmann@outlook.com
description: Aspiring Software, Website and Game Developer <br /> Join me on my journey!
baseurl: "/personal" # the subpath of your site, e.g. /blog
url: https://buxmann.dev # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code:
country:
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/mbuxmann
gitlab_url: https://gitlab.com/u/bitVivAZ
googleplus_url: 
instagram_url: https://instagram.com/bitVivAZ
linkedin_url: https://www.linkedin.com/in/mabuxmann/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/bitVivAZ

# build settings
markdown: kramdown

sass:
  style: compressed

# collections
collections:
  gamedev:
    output: true
  softwaredev:
    output: true
  webdev:
    output: true
